version: '3'
services:
  web:
    build: ./Frontend/
    ports:
      - "8080-8090:80"
    depends_on:
      - database
      
  database:
    build: ./Backend/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: Adeel
      POSTGRES_PASSWORD: Adeel123

