# Use an official PostgreSQL image as the base image
FROM postgres:latest

# Environment variables to set up the database
ENV POSTGRES_DB mydatabase
ENV POSTGRES_USER Adeel
ENV POSTGRES_PASSWORD Adeel123

# Expose the default PostgreSQL port
EXPOSE 5432

